name: authentication
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.7
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true